### ISSUE TITLE
Where can I find versioned Docker images?

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/fiware-orion-pyspark-connector#23]
I'm looking to use the pyspark connector, but I  can't find the **Versioned** images anyway - there is no link on the README, could you advice me as to where to find them?

There is one **latest** image  found at: rdlabengpa/fiware-orion-pyspark-connector but there is no version tag to obtain stable images.

**Comment by emiliocimino** [comment]
Dear Jason,
we are currently working on moving the docker image to quay. As soon we have the docker image ready we will update the docker section and every related link. Meanwhile, we would provide a stable tag in the current repository if needed.

Thanks

**Comment by jason-fox** [comment]
I have been informed that the current Engineering source of Docker Images is here: https://hub.docker.com/r/rdlabengpa/fiware-orion-pyspark-connector/tags - closing as completed.
